apiVersion: apps/v1  # Menentukan versi API yang digunakan
kind: Deployment  # Mendefinisikan tipe sumber daya Kubernetes sebagai Deployment.
metadata:
  name: order-service-deploy  # Nama sumber daya Deployment
spec:
  replicas: 1  # Menentukan jumlah replika untuk Deployment
  selector:
    matchLabels:
      app: order-service  # Memilih Pod berdasarkan label "app" dengan nilai "order-service"
  template:
    metadata:
      labels:
        app: order-service  # Memberi label pada Pod yang dibuat oleh template ini dengan label "app" dan nilai "order-service"
    spec:
      containers:
        - name: order-service  # Nama kontainer dalam Pod
          image: docker.pkg.github.com/mitubaby/a433-microservices/order-service:latest  # Image Docker yang digunakan untuk kontainer
          ports:
            - containerPort: 3000  # Port yang digunakan untuk mendengarkan lalu lintas masuk
          env:
            - name: AMQP_PASSWORD  # Nama variabel lingkungan untuk kata sandi RabbitMQ
              valueFrom:
                secretKeyRef:
                  name: my-rabbitmq  # Nama rahasia yang berisi kata sandi RabbitMQ
                  key: rabbitmq-password  # Kunci rahasia untuk mengambil kata sandi RabbitMQ
            - name: AMQP_URL  # Nama variabel lingkungan untuk URL RabbitMQ
              value: "amqp://user:$(AMQP_PASSWORD)@my-rabbitmq:5672"  # Nilai untuk URL RabbitMQ, termasuk nama pengguna, kata sandi, dan host
