apiVersion: v1  # Menentukan versi API yang digunakan
kind: Service  # Mendefinisikan jenis sumber daya Kubernetes sebagai Service
metadata:
  name: order-service-svc  # Nama yang diberikan pada sumber daya Service ini
spec:
  selector:
    app: order-service  # Memilih pod yang diberi label 'app: order-service'
  ports:
    - port: 3000  # Mengekspos Service ini pada port 3000 dengan menggunakan protokol TCP
